In [1]:
import numpy as np

In [2]:
a = np.arange(1 ,11)
b = np.add.reduce(a)
c = np.add.accumulate(a)
d = np.multiply.reduce(a)
e = np.multiply.accumulate(a)
print (" a = {} ".format(a)); print (" b = {} ".format(b));
print (" c = {} ".format(c)); print (" d = {} ".format(d));
print (" e = {} ".format(e))


 a = [ 1  2  3  4  5  6  7  8  9 10] 
 b = 55 
 c = [ 1  3  6 10 15 21 28 36 45 55] 
 d = 3628800 
 e = [      1       2       6      24     120     720    5040   40320  362880
 3628800] 


In [3]:
a = np.array([[1,2,3],[10,20,30],[100,200,300]])
b = np.add.reduce(a,0)
c = np.add.reduce(a,1)
d = np.add.reduce(a)
print (" a = {} ".format(a)); print (" b = {} ".format(b));
print (" c = {} ".format(c)); print (" d = {} ".format(d))



 a = [[  1   2   3]
 [ 10  20  30]
 [100 200 300]] 
 b = [111 222 333] 
 c = [  6  60 600] 
 d = [111 222 333] 


In [4]:
a = np.array([[1,2,3],[10,20,30],[100,200,300]])
b = np.add.reduce(a,0)
c = np.add.reduce(a,1)
d = np.add.reduce(a)
print (" a = {} ".format(a)); print (" b = {} ".format(b));
print (" c = {} ".format(c)); print (" d = {} ".format(d))
a = np.array ([1,2,3,4,5,6,7,8,9,10])
b = np.array ([[1,2,3],[10,20,30],[100,200,300]])
c = a.max()
d = a.min()
e = np.max(b,0)
f = np.min(b,0)
g = np.max(b,1)
h = np.min(b,1)
i = np.max(b)
j = np.min(b)
print (" a = {} ".format(a)); print (" b = {} ".format(b));
print (" c = {} ".format(c)); print (" d = {} ".format(d));
print (" e = {} ".format(e)); print (" f = {} ".format(f));
print (" g = {} ".format(g)); print (" h = {} ".format(h));
print (" i = {} ".format(i)); print (" j = {} ".format(j));


 a = [[  1   2   3]
 [ 10  20  30]
 [100 200 300]] 
 b = [111 222 333] 
 c = [  6  60 600] 
 d = [111 222 333] 
 a = [ 1  2  3  4  5  6  7  8  9 10] 
 b = [[  1   2   3]
 [ 10  20  30]
 [100 200 300]] 
 c = 10 
 d = 1 
 e = [100 200 300] 
 f = [1 2 3] 
 g = [  3  30 300] 
 h = [  1  10 100] 
 i = 300 
 j = 1 
